import type { Localized } from './types'

export const ui = {
  'meta.title': {
    pt: 'Victor Crepaldi — Desenvolvedor Full Stack',
    en: 'Victor Crepaldi — Full Stack Developer',
  },
  'meta.description': {
    pt: 'Desenvolvedor Full Stack em Dracena/SP. Construo interfaces limpas e rápidas com React, TypeScript e Node.js.',
    en: 'Full Stack Developer based in Brazil. I build clean, fast interfaces with React, TypeScript and Node.js.',
  },

  'a11y.skip': { pt: 'Pular para o conteúdo', en: 'Skip to content' },
  'a11y.mainNav': { pt: 'Navegação principal', en: 'Main navigation' },
  'a11y.toggleTheme': { pt: 'Alternar tema', en: 'Toggle theme' },
  'a11y.toggleLang': { pt: 'Alternar idioma', en: 'Toggle language' },
  'a11y.openMenu': { pt: 'Abrir menu', en: 'Open menu' },
  'a11y.closeMenu': { pt: 'Fechar menu', en: 'Close menu' },
  'a11y.openCommand': { pt: 'Abrir paleta de comandos', en: 'Open command palette' },
  'a11y.home': { pt: 'Ir para o início', en: 'Go to top' },

  'status.available': {
    pt: 'Disponível para novas oportunidades',
    en: 'Available for new opportunities',
  },
  'status.unavailable': { pt: 'Agenda fechada no momento', en: 'Not available right now' },

  'hero.scroll': { pt: 'Role para explorar', en: 'Scroll to explore' },
  'hero.cta.work': { pt: 'Ver projetos', en: 'View work' },
  'hero.cta.contact': { pt: 'Entrar em contato', en: 'Get in touch' },
  'hero.stat.repos': { pt: 'Repositórios', en: 'Repositories' },
  'hero.stat.commits': { pt: 'Contribuições / ano', en: 'Contributions / year' },
  'hero.stat.age': { pt: 'Anos', en: 'Years old' },
  'hero.stat.since': { pt: 'No GitHub desde', en: 'On GitHub since' },

  'about.title': { pt: 'Sobre', en: 'About' },
  'about.lead': { pt: 'Quem eu sou e com o que trabalho.', en: 'Who I am and what I work with.' },
  'about.stack': { pt: 'Stack', en: 'Stack' },
  'about.focus': { pt: 'Foco', en: 'Focus' },
  'about.resume': { pt: 'Currículo', en: 'Résumé' },
  'about.diploma': { pt: 'Diploma', en: 'Diploma' },

  'experience.title': { pt: 'Trajetória', en: 'Path' },
  'experience.lead': { pt: 'Onde trabalhei e onde estudei.', en: "Where I've worked and studied." },
  'experience.current': { pt: 'Atual', en: 'Current' },
  'experience.education': { pt: 'Formação', en: 'Education' },

  'work.title': { pt: 'Projetos', en: 'Work' },
  'work.lead': { pt: 'Projetos que construí.', en: "Projects I've built." },
  'work.all': { pt: 'Todos', en: 'All' },
  'work.empty': { pt: 'Nenhum projeto nesta categoria.', en: 'No projects in this category.' },
  'work.repo': { pt: 'Repositório', en: 'Repository' },
  'work.demo': { pt: 'Ver online', en: 'Live demo' },
  'work.highlights': { pt: 'O que tem dentro', en: "What's inside" },
  'work.updated': { pt: 'Atualizado', en: 'Updated' },

  'github.title': { pt: 'GitHub', en: 'GitHub' },
  'github.lead': { pt: 'Direto do meu GitHub.', en: 'Straight from my GitHub.' },
  'github.repos': { pt: 'Repositórios', en: 'Repositories' },
  'github.stars': { pt: 'Estrelas', en: 'Stars' },
  'github.followers': { pt: 'Seguidores', en: 'Followers' },
  'github.contributions': { pt: 'Contribuições no último ano', en: 'Contributions in the last year' },
  'github.languages': { pt: 'Linguagens', en: 'Languages' },
  'github.recent': { pt: 'Repositórios recentes', en: 'Recent repositories' },
  'github.viewProfile': { pt: 'Ver perfil no GitHub', en: 'View GitHub profile' },
  'github.less': { pt: 'Menos', en: 'Less' },
  'github.more': { pt: 'Mais', en: 'More' },
  'github.contributionOn': { pt: 'contribuições em', en: 'contributions on' },
  'github.live': { pt: 'Sincronizado', en: 'Synced' },
  'github.streak': { pt: 'Maior sequência', en: 'Longest streak' },
  'github.busiest': { pt: 'Dia mais ativo', en: 'Busiest day' },
  'github.days': { pt: 'dias', en: 'days' },

  'contact.title': { pt: 'Contato', en: 'Contact' },
  'contact.lead': { pt: 'Quer conversar? Escolha o canal.', en: 'Want to talk? Pick a channel.' },
  'contact.pitch': {
    pt: 'Aberto a oportunidades presenciais na região de Dracena/SP ou remotas.',
    en: 'Open to roles on-site around Dracena, Brazil, or remote.',
  },
  'contact.copy': { pt: 'Copiar', en: 'Copy' },
  'contact.copied': { pt: 'Copiado', en: 'Copied' },
  'contact.responseTime': { pt: 'Respondo em até 24h', en: 'I reply within 24h' },

  'footer.built': { pt: 'Feito com', en: 'Built with' },
  'footer.backToTop': { pt: 'Voltar ao topo', en: 'Back to top' },
  'footer.navigate': { pt: 'Navegar', en: 'Navigate' },
  'footer.myTime': { pt: 'Meu horário local', en: 'My local time' },
  'footer.version': { pt: 'Versão deste site', en: 'Version of this site' },

  'music.title': { pt: 'Música', en: 'Music' },
  'music.open': { pt: 'Abrir player', en: 'Open player' },
  'music.close': { pt: 'Fechar player', en: 'Close player' },
  'music.lead': {
    pt: 'Cole um link do YouTube ou escolha uma estação para ouvir enquanto navega.',
    en: 'Paste a YouTube link or pick a station to listen while you browse.',
  },
  'music.placeholder': { pt: 'Link ou ID do YouTube', en: 'YouTube link or ID' },
  'music.play': { pt: 'Tocar', en: 'Play' },
  'music.stations': { pt: 'Estações', en: 'Stations' },
  'music.invalid': { pt: 'Não consegui ler esse link.', en: "I couldn't read that link." },
  'music.searchOn': { pt: 'Buscar no YouTube', en: 'Search on YouTube' },
  'music.searchHint': {
    pt: 'Procure a música, copie o link e cole aqui.',
    en: 'Find the track, copy its link and paste it here.',
  },
  'music.nowPlaying': { pt: 'Tocando agora', en: 'Now playing' },
  'music.stop': { pt: 'Parar', en: 'Stop' },
  'music.minimize': { pt: 'Minimizar player', en: 'Minimise player' },
  'music.pause': { pt: 'Pausar', en: 'Pause' },
  'music.seek': { pt: 'Posição da faixa', en: 'Track position' },
  'music.volume': { pt: 'Volume', en: 'Volume' },
  'music.mute': { pt: 'Silenciar', en: 'Mute' },
  'music.unmute': { pt: 'Ativar som', en: 'Unmute' },
  'music.loading': { pt: 'Carregando…', en: 'Loading…' },
  'music.liveStream': { pt: 'Transmissão ao vivo', en: 'Live stream' },
  'music.unavailable': { pt: 'Faixa indisponível', en: 'Track unavailable' },
  'music.tryAnother': { pt: 'Escolha outra ou cole um link', en: 'Pick another or paste a link' },

  'cmd.placeholder': { pt: 'Buscar ou digitar um comando…', en: 'Search or type a command…' },
  'cmd.empty': { pt: 'Nenhum resultado.', en: 'No results found.' },
  'cmd.nav': { pt: 'Navegar', en: 'Navigate' },
  'cmd.projects': { pt: 'Projetos', en: 'Projects' },
  'cmd.actions': { pt: 'Ações', en: 'Actions' },
  'cmd.links': { pt: 'Links', en: 'Links' },
  'cmd.theme.light': { pt: 'Tema claro', en: 'Light theme' },
  'cmd.theme.dark': { pt: 'Tema escuro', en: 'Dark theme' },
  'cmd.theme.system': { pt: 'Tema do sistema', en: 'System theme' },
  'cmd.lang.pt': { pt: 'Mudar para Português', en: 'Switch to Portuguese' },
  'cmd.lang.en': { pt: 'Mudar para Inglês', en: 'Switch to English' },
  'cmd.copyEmail': { pt: 'Copiar e-mail', en: 'Copy email' },
  'cmd.resume': { pt: 'Abrir currículo', en: 'Open résumé' },
  'cmd.top': { pt: 'Ir para o topo', en: 'Go to top' },
  'cmd.music': { pt: 'Tocar música', en: 'Play music' },

  'egg.snake.title': { pt: 'Snake', en: 'Snake' },
  'egg.snake.start': { pt: 'Pressione ESPAÇO para começar', en: 'Press SPACE to start' },
  'egg.snake.paused': { pt: 'Pausado', en: 'Paused' },
  'egg.snake.over': { pt: 'Fim de jogo', en: 'Game over' },
  'egg.snake.score': { pt: 'Pontos', en: 'Score' },
  'egg.snake.best': { pt: 'Recorde', en: 'Best' },
  'egg.snake.again': { pt: 'Jogar de novo', en: 'Play again' },
  'egg.snake.controls': {
    pt: 'Setas ou WASD para mover · ESPAÇO pausa',
    en: 'Arrows or WASD to move · SPACE pauses',
  },
  'egg.snake.found': { pt: 'Você encontrou o Snake.', en: 'You found the Snake.' },

  'egg.love.found': { pt: 'Então você me encontrou.', en: 'So you found me.' },
} as const satisfies Record<string, Localized>

export type UiKey = keyof typeof ui
